function h1 = Helptab()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the MATLAB file at the MATLAB
% prompt. The MATLAB code file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the MATLAB code file/MAT-file format, and should be saved as
% FIG-files.


load Helptab.mat


appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'Position',[135.8 46.2307692307692 117.4 38.1538461538462],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',[0.2 0.8 1],...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','Mooshik- The MATLAB Music Player!',...
'NumberTitle','off',...
'Tag','figure1',...
'DockControls','off',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'ScreenPixelsPerInchMode','manual',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title',blanks(0),...
'Position',[5.8 1.76923076923077 104.2 28.6153846153846],...
'BackgroundColor',[0 0.447058823529412 0.741176470588235],...
'Tag','uipanel1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text6';

h3 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'Mooshik is every ASE''s favourite tool when on PDT/Support. You can easily decode stack traces or develop applications or even debug AUTOSAR models while jiving comfortably to your favourite tunes, all from the same desktop environment of our friendly-neighbourhood MATLAB'; 'This is the app that will add to your support/PDT efforts in brilliant proportions.'; blanks(0); 'Developed by arvindn'; 'Any queries/concerns, mail to Arvind.Narayanan@mathworks.in or contact +91-80-6632-5048' },...
'Style','text',...
'Position',[7.8 1.53846153846154 82.4 25.5384615384615],...
'BackgroundColor',[0 0.447058823529412 0.741176470588235],...
'Children',[],...
'ForegroundColor',[1 1 1],...
'Tag','text6',...
'FontSize',14,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text5';

h4 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Mooshik - The MATLAB Music Player!',...
'Style','text',...
'Position',[7.8 32.2307692307692 96.8 4.30769230769231],...
'BackgroundColor',[0 0.8 1],...
'Children',[],...
'Tag','text5',...
'FontSize',20,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end
